//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestTask.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartTestTask.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key is not configured.
        /// </summary>
        internal static string Api_ApiKeyNotConfigured {
            get {
                return ResourceManager.GetString("Api_ApiKeyNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key was not provided.
        /// </summary>
        internal static string Api_ApiKeyNotProvided {
            get {
                return ResourceManager.GetString("Api_ApiKeyNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API Key.
        /// </summary>
        internal static string Api_InvalidApiKey {
            get {
                return ResourceManager.GetString("Api_InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract is already deactivated.
        /// </summary>
        internal static string Contract_AlreadyDeactivated {
            get {
                return ResourceManager.GetString("Contract_AlreadyDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create contract.
        /// </summary>
        internal static string Contract_CreationFailed {
            get {
                return ResourceManager.GetString("Contract_CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deactivate contract.
        /// </summary>
        internal static string Contract_DeactivationFailed {
            get {
                return ResourceManager.GetString("Contract_DeactivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID mismatch.
        /// </summary>
        internal static string Contract_IdMismatch {
            get {
                return ResourceManager.GetString("Contract_IdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment quantity must be greater than zero.
        /// </summary>
        internal static string Contract_InvalidQuantity {
            get {
                return ResourceManager.GetString("Contract_InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract with ID &apos;{0}&apos; was not found.
        /// </summary>
        internal static string Contract_NotFound {
            get {
                return ResourceManager.GetString("Contract_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update contract.
        /// </summary>
        internal static string Contract_UpdateFailed {
            get {
                return ResourceManager.GetString("Contract_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area must be greater than zero.
        /// </summary>
        internal static string Equipment_InvalidArea {
            get {
                return ResourceManager.GetString("Equipment_InvalidArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment type code cannot be empty.
        /// </summary>
        internal static string Equipment_InvalidCode {
            get {
                return ResourceManager.GetString("Equipment_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment type name cannot be empty.
        /// </summary>
        internal static string Equipment_InvalidName {
            get {
                return ResourceManager.GetString("Equipment_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process equipment type with code &apos;{0}&apos; was not found.
        /// </summary>
        internal static string Equipment_NotFound {
            get {
                return ResourceManager.GetString("Equipment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient area in facility {0}. Required: {1} m², Available: {2} m².
        /// </summary>
        internal static string Facility_InsufficientArea {
            get {
                return ResourceManager.GetString("Facility_InsufficientArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard area must be greater than zero.
        /// </summary>
        internal static string Facility_InvalidArea {
            get {
                return ResourceManager.GetString("Facility_InvalidArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production facility code cannot be empty.
        /// </summary>
        internal static string Facility_InvalidCode {
            get {
                return ResourceManager.GetString("Facility_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production facility name cannot be empty.
        /// </summary>
        internal static string Facility_InvalidName {
            get {
                return ResourceManager.GetString("Facility_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production facility with code &apos;{0}&apos; was not found.
        /// </summary>
        internal static string Facility_NotFound {
            get {
                return ResourceManager.GetString("Facility_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was modified by another user.
        /// </summary>
        internal static string General_ConcurrencyConflict {
            get {
                return ResourceManager.GetString("General_ConcurrencyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database error occurred.
        /// </summary>
        internal static string General_DatabaseError {
            get {
                return ResourceManager.GetString("General_DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access forbidden.
        /// </summary>
        internal static string General_Forbidden {
            get {
                return ResourceManager.GetString("General_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        internal static string General_NotFound {
            get {
                return ResourceManager.GetString("General_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        internal static string General_Unauthorized {
            get {
                return ResourceManager.GetString("General_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        internal static string General_UnexpectedError {
            get {
                return ResourceManager.GetString("General_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        internal static string Validation_Failed {
            get {
                return ResourceManager.GetString("Validation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must match format: {1}.
        /// </summary>
        internal static string Validation_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input for field: {0}.
        /// </summary>
        internal static string Validation_InvalidInput {
            get {
                return ResourceManager.GetString("Validation_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must not exceed {1} characters.
        /// </summary>
        internal static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required.
        /// </summary>
        internal static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation_RequiredField", resourceCulture);
            }
        }
    }
}
